apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring
  namespace: gitlab-runners
  labels:
    app: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: spring-boot
        image: registry.cn-hangzhou.aliyuncs.com/tmp-images/hello-spring:v0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            port: 5000
            path: /healthz
            scheme: HTTP
          periodSeconds: 15
          initialDelaySeconds: 30
      serviceAccountName: gitlab      
