apiVersion: v1
kind: Service
metadata:
  name: spring-boot
  namespace: gitlab-runners
  labels:
    app: spring-boot
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 8888
  selector:
    app: spring-boot
