spring:
  redis:
    host: 172.17.218.94
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: -1 	# 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 	# 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8		# 连接池中的最大空闲连接
        min-idle: 0		# 连接池中的最小空闲连接
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
server:
  port: 8080